# organization name, it's used to get github repo url, also in page title
name: bemusic

# badge style, can be "flat", "flat-square" or ""
# see http://shields.io/ for details
badge_style: flat

# meta headers in html
title:       BEMUSE Project
description: Web-based BMS simulator
keywords:    bms, rhythm, game

# list of projects, this will be sorted by name;
# every package is either string or object
projects:
 - bemuse
 - pack
 - bms-js

# list of maintainers, this won't be sorted
maintainers:
 - name:    dtinth
   github:  dtinth   # github account, required: we link to it
   npm:     dtinth   # npm account, required to determine lead maintainer
   twitter: dtinth   # twitter account, optional
   gittip:  dtinth   # gittub badge, optional
   email:   dtinth@spacet.me

# this determines what info will be fetched with `make db`;
# you can comment out stuff to reduce number of http requests
db.json:
  projects:
   - node        # node version, it's the lowest version from .travis.yml
   - description # package description from package.json (from npm registry)
   #- maintainer  # maintainer npm account (= _npmUser of last published ver)
  maintainers:
   - packages    # amount of packages this npm user has
